---
title: "LAB 2"
author: "Bhumika Subedi-Giri"
date: "1/29/2020"
output: html_document
---
### Exercise 1
```{r}
A <- c(1,3,6,9,12)
B <- c(1,0,1,0,1)
A+B
A-B
A*B
A/B

```
### Exercise 2
```{r}
A <- c(0, 1, 2, 3)
B <- c("aa", "bb", "cc", "dd")
C <- c("aa", 1, "bb", 2)

str(A)
str(B)
str(C)
```
### Exercise 3
```{r}
Genotype1 <- c("AA", "AA", "AG", "GG", "GG")
Genotype2 <- c("AA", "AA", "GG", "GG", "GG")
B <- cbind(Genotype1, Genotype2)
B

table(Genotype1)
table(Genotype2)
```
### Exercise 4
```{r}
Treatment1 <- c(0, 1, 2, 3, 4)
Treatment2 <- c(0, 2, 4, 6, 8)
Treatment3 <- c(0, 3, 6, 9, 12)
times <- c(0, 2, 4, 6, 8)

Treatment <- data.frame(Treatment1, Treatment2, Treatment3, row.names = times)
Treatment

Treatment$times <- c(0, 2, 4, 6, 8)
Treatment

plot(Treatment$Treatment3, Treatment$times)
```
### Exercise 5
```{r}
SNP_table <- read.table("23andMe_complete.txt", header = TRUE, sep = "\t")

str(SNP_table)
```

This chromosome is shown to  be a factor.
Truncated version only  has numbers and has no characters. However, in this file, there are characters which means that there is a mix between numbers and characters or it only has characters.

### Exercise 6
```{r}
table(SNP_table$genotype)
```
### Exercise 7
```{r}
SNP_table_A <- subset(SNP_table, genotype == 'A')
table(SNP_table_A$chromosome)
```
