---
title: "Lab_5"
author: "Bhumika Subedi-Giri"
date: "2/19/2020"
output: html_document
---

```{r}
download.file(url="https://ndownloader.figshare.com/files/2292169",
              destfile = "data/portal_data_joined.csv")
```

```{r setup, include=FALSE}
library (tidyverse)
surveys <- read_csv("data/portal_data_joined.csv")
```


```{r}
SNPs <- read_tsv("data/23andMe_complete.txt", skip = 14, col_types = 
  cols(chromosome = col_factor()))
```

##Challenge 1
```{r}
surveys %>%
    filter(year < 1995) %>%
    select(year, sex, weight)
```

##Challenge 2
```{r}
surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    mutate(hindfoot_half = hindfoot_length / 2) %>%
    filter(hindfoot_half < 30) %>%
    select(species_id, hindfoot_half)
```

##Challenge 3A
```{r}
surveys %>%
    count(plot_type) 
```

##3B
```{r}
surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    group_by(species_id) %>%
    summarize(
        mean_hindfoot_length = mean(hindfoot_length),
        min_hindfoot_length = min(hindfoot_length),
        max_hindfoot_length = max(hindfoot_length),
        n = n()
    )
```

##3C
```{r}
surveys %>%
    filter(!is.na(weight)) %>%
    group_by(year) %>%
    filter(weight == max(weight)) %>%
    select(year, genus, species, weight) %>%
    arrange(year)
```

##Challenge 4A
```{r}
rich_time <- surveys %>%
  group_by(plot_id, year) %>%
  summarize(n_genera = n_distinct(genus)) %>%
  spread(year, n_genera)

head(rich_time)
```

##4B
```{r}
rich_time %>%
  gather(year, n_genera, -plot_id)
```

##4C
```{r}
surveys_long <- surveys %>%
  gather(measurement, value, hindfoot_length, weight)
```

##4D
```{r}
surveys_long %>%
  group_by(year, measurement, plot_type) %>%
  summarize(mean_value = mean(value, na.rm=TRUE)) %>%
  spread(measurement, mean_value)
```

##Exercise 1
```{r}
SNPs %>%
  select(position, genotype)
```

##Exercise 2
```{r}  
SNPs %>%
  filter(chromosome =="MT") %>%
  filter(genotype!="A") %>%
  filter(genotype!="B")     
```

##Exercise 3
```{r}
SNPs %>%
  group_by(chromosome)%>%
  summarize (
          (min_position= min(position)),
          (max_position= max(position)),
          count=n()
  )        
```

##Exercise 4
```{r}
SNPs %>%
  group_by(chromosome) %>% 
  summarize(
          min_position=min(position),
          max_position=max(position),
          count=n()
) %>% 
mutate(density=count/(max_position-min_position))
```

##Exercise 5
```{r}
SNPs %>%
  group_by(chromosome) %>% 
  summarize(
          min_position=min(position),
          max_position=max(position),
          count=n()
) %>% 
mutate(density=count/(max_position-min_position)) %>% 
count(chromosome,density) %>% 
arrange(density)
```

##Exercise 6
```{r}
SNPs<-SNPs %>% 
      group_by(chromosome) %>% 
      summarize(
            min_position=min(position),
            max_position=max(position),
            count=n()
) %>% 
mutate(density=count/(max_position-min_position)) %>% 
count(chromosome,density) %>% 
arrange(density)
write_csv(SNPs,path="data/Lab5_Exercise5")
```






